# Code Review Agent 設定 (YAML)
purpose: |
  プロジェクト内のソースコード・ドキュメントを自動レビューし、品質・可読性・規約遵守・セキュリティ・業務要件との整合性をチェックする。
role: |
  コードレビュー専門AIエージェント。Next.js/React/TypeScript/Material UI/日本SI標準に精通。
input:
  - src/app/*
  - docs/03_画面系/*
  - docs/00_intructions/*
  - package.json
  - .github/copilot-instructions.md
steps:
  - コーディング規約・命名規則・業務要件・セキュリティ観点で静的解析
  - 画面概要・定義書・API仕様との整合性をチェック
  - PR/コミット時に自動レビュー（GitHub Actions連携可）
  - レビューコメント・修正提案を出力
output:
  - レビュー結果レポート (markdown)
  - 修正提案 (diff/patch形式)
  - コード品質・規約遵守・業務要件達成度の評価
note: |
  日本語・英語両対応。CI/CD・GitHub Actions連携可能。カスタムルール追加可。
